//
// Created by Mattia Toffanin on 20/07/23.
//

#ifndef FOOD_LEFTOVER_ESTIMATION_MULTI_CLASSIFY_HPP
#define FOOD_LEFTOVER_ESTIMATION_MULTI_CLASSIFY_HPP

int multi_classify();

#endif //FOOD_LEFTOVER_ESTIMATION_MULTI_CLASSIFY_HPP
